// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"gorm.io/gorm"
	"mcp_demo/controllers"
	"mcp_demo/repositories"
	"mcp_demo/routes"
	"mcp_demo/services"
)

import (
	_ "gorm.io/gorm"
	_ "mcp_demo/controllers"
	_ "mcp_demo/docs"
	_ "mcp_demo/repositories"
	_ "mcp_demo/routes"
	_ "mcp_demo/services"
)

// Injectors from wire.go:

func InitializeRouter(db *gorm.DB) (*routes.Router, error) {
	noteRepository := repositories.NewNoteRepository(db)
	noteService := services.NewNoteService(noteRepository)
	noteController := controllers.NewNoteController(noteService)
	router := routes.NewRouter(noteController)
	return router, nil
}
